project_id = "cguzpetufoftdqxwqygh"

[functions.ghl-fetch-config]
verify_jwt = false

[functions.ghl-submit]
verify_jwt = false

[functions.project-recommendations]
verify_jwt = false

[functions.room-visualizer]
verify_jwt = false

[functions.voice-transcribe]
verify_jwt = false
